### ISSUE TITLE
Mistake in sentence in the game

### ISSUE THREAD

**Issue by NiksheyYadav** [tusharhero/darwinio#13]
I found an English error in adjust settings.

**Comment by tusharhero** [comment]
I would it appreciate if you could point out the mistake and perhaps give me a PR fixing the mistake.

**Comment by NiksheyYadav** [comment]
Greetings sirs!
I have a question which I have been pondering upon since this question was posted


Where do I have to change the code?

**Comment by tusharhero** [comment]
You can find it in `src/darwinio/__main__.py` or `src/darwinio/graphic_sim.py`.

**Comment by tusharhero** [comment]
Thank you for your help, I have fixed it in a849c81. Hence I am closing this issue.
